#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn install

echo Linting
yarn run lint

echo Type Checking App
yarn run check:app

echo Type Checking Components
yarn run check:components

echo Testing application
yarn test:app

echo Testing components
yarn test:components
